import Config

# Default to a local Postgres on the standard port. Override with DATABASE_URL.
config :crucible, Crucible.Repo,
  url: System.get_env("DATABASE_URL") || "postgresql://localhost:5432/crucible_dev",
  stacktrace: true,
  show_sensitive_data_on_connection_error: true,
  pool_size: 10,
  queue_target: 50,
  queue_interval: 1000,
  backoff_type: :rand_exp,
  backoff_min: 200,
  backoff_max: 15_000,
  disconnect_on_error_codes: [:admin_shutdown]

# Default dev database is empty until `mix ecto.setup` runs the Phoenix
# migrations. Keep Oban plugins off by default so a fresh checkout boots
# without errors; opt in once leadership tables exist.
if System.get_env("OBAN_ENABLE_PLUGINS", "false") != "true" do
  config :crucible, Oban,
    peer: false,
    plugins: false,
    queues: false
end

# Pending-migration check is opt-in for dev. Set PHX_CHECK_PENDING_MIGRATIONS=true
# to enforce it locally.
config :crucible,
  check_pending_migrations_in_dev:
    System.get_env("PHX_CHECK_PENDING_MIGRATIONS", "false") == "true"

# For development, we disable any cache and enable
# debugging and code reloading.
#
# The watchers configuration can be used to run external
# watchers to your application. For example, we can use it
# to bundle .js and .css sources.
#
# `secret_key_base` is an ephemeral compile-time placeholder — the real value
# is resolved from `.env` / the shell in `config/runtime.exs` (which warns
# there if unset). Resolving here would fire spuriously, because `.env` is
# hydrated by `Crucible.DotenvLoader` in `runtime.exs`, which runs later.
config :crucible, CrucibleWeb.Endpoint,
  # Binding to loopback ipv4 address prevents access from other machines.
  # Change to `ip: {0, 0, 0, 0}` to allow access from other machines.
  http: [ip: {127, 0, 0, 1}, port: String.to_integer(System.get_env("PORT", "4801"))],
  check_origin: false,
  code_reloader: true,
  debug_errors: true,
  secret_key_base: :crypto.strong_rand_bytes(48) |> Base.encode64(),
  watchers: [
    esbuild: {Esbuild, :install_and_run, [:crucible, ~w(--sourcemap=inline --watch)]},
    tailwind: {Tailwind, :install_and_run, [:crucible, ~w(--watch)]}
  ]

# ## SSL Support
#
# In order to use HTTPS in development, a self-signed
# certificate can be generated by running the following
# Mix task:
#
#     mix phx.gen.cert
#
# Run `mix help phx.gen.cert` for more information.
#
# The `http:` config above can be replaced with:
#
#     https: [
#       port: 4001,
#       cipher_suite: :strong,
#       keyfile: "priv/cert/selfsigned_key.pem",
#       certfile: "priv/cert/selfsigned.pem"
#     ],
#
# If desired, both `http:` and `https:` keys can be
# configured to run both http and https servers on
# different ports.

# Reload browser tabs when matching files change.
config :crucible, CrucibleWeb.Endpoint,
  live_reload: [
    web_console_logger: true,
    patterns: [
      # Static assets, except user uploads
      ~r"priv/static/(?!uploads/).*\.(js|css|png|jpeg|jpg|gif|svg)$"E,
      # Gettext translations
      ~r"priv/gettext/.*\.po$"E,
      # Router, Controllers, LiveViews and LiveComponents
      ~r"lib/crucible_web/router\.ex$"E,
      ~r"lib/crucible_web/(controllers|live|components)/.*\.(ex|heex)$"E
    ]
  ]

# Enable dev routes for dashboard and mailbox
config :crucible, dev_routes: true

# Do not include metadata nor timestamps in development logs
config :logger, :default_formatter, format: "[$level] $message\n"

# Set a higher stacktrace during development. Avoid configuring such
# in production as building large stacktraces may be expensive.
config :phoenix, :stacktrace_depth, 20

# Initialize plugs at runtime for faster development compilation
config :phoenix, :plug_init_mode, :runtime

config :phoenix_live_view,
  # Include debug annotations and locations in rendered markup.
  # Changing this configuration will require mix clean and a full recompile.
  debug_heex_annotations: true,
  debug_attributes: true,
  # Enable helpful, but potentially expensive runtime checks
  enable_expensive_runtime_checks: true
